SQL5完成しました
takahashi-166-20/projectP2020_166 pull request #21
Opened 2020-07-26 05:37 UTC by takahashi-166-20

2020-07-27 11:37 UTC, jotasugiyama requested changes
検索 > 出てきたレコードの更新を行いたいのですがうまくいきません。
そもそも検索ができない状況なのですが、私の環境だからなのかなー？
ちなみに、高橋くんは検索できますか？

2020-07-27 11:37 UTC, jotasugiyama commented on ex3/sql5_client.html
> +    <button id = "slct_btn" onclick ="slct_addresses()">select name in SQL4</button></br>
select name in SQL4っていうボタンは検索のことですかー？
もうすこしわかり易い名前にしたほうが見やすいと思います！
`検索` や `search` など・・・

2020-07-27 11:37 UTC, jotasugiyama commented on ex3/sql5_client.html
> +        var chg_btn = document.getElementById("chg_btn");
これらの変数で使用していないものは削除して下さいー！

2020-07-27 11:37 UTC, jotasugiyama commented on ex3/sql5_client.html
> +    <input id = "slct_name">
何のフォームなのかがわかりにくいので、下記のようにわかりやすくしてください！

```html
名前: <input id="name">
住所: <input id="phone">
...
```

2020-07-27 11:46 UTC, jotasugiyama requested changes

2020-07-27 11:46 UTC, jotasugiyama commented on ex3/sql5_client.html
> +            req4.open("GET","sql5_server.php?chg_id="+chg_id.value+"&chg_name="+chg_name.value+"&chg_address="+chg_address.value+"&chg_phone="+chg_phone.value+"&chg_email="+chg_email.value,true);
ここのコードの治安があまりよくないです。
実装が私の環境で見れないので、コードからの推測になってしまいますが、多分この場合、`名前だけ`を更新したい時に、名前以外が空白になるため、住所や電話番号が空白になってしまうと思います。
なので、その点を含めて以下のことを修正して下さい

1. 一度変数に挿入して下さい（そのほうが綺麗です）
```javascript
// 例
var updateName = chg_name.value
var id = chg_id.value
```

2. 空欄だった場合の処理を追加
```javascript
// 例 名前が空白だったら、もともとのレコード情報を挿入する

if (updateName === "") {
    updateName = もともと入っている名前を入れる
}
```

下記のポイントを修正してほしいです。

2020-07-29 11:52 UTC, takahashi-166-20 commented
1.更新がうまくいかなかった理由について：PHP側のソース24行目に後からアンダーバーを追加したことを失念していました、大変申し訳ございません。
2.使用していない変数について：「課題6を作成するにあたって、今までの課題を分けて作成していた場合、課題2～5の機能を追加すること」とありましたが、別々に作成して課題6で全て機能を追加するよりも課題2のソースを元に機能を追加していく方が効率的であると考えたので、課題4までの機能で使用している変数も入れておいたのですが、これは削除しておいた方がよいでしょうか？
3.更新しないカラムが空白になってしまう問題について：HTML側でupdateNameに値を代入する方法が思いつかなかったので、PHP側のソース17～26行目までで処理を行いました。

2020-07-29 15:29 UTC, jotasugiyama commented
> 1.更新がうまくいかなかった理由について：PHP側のソース24行目に後からアンダーバーを追加したことを失念していました、大変申し訳ございません。
2.使用していない変数について：「課題6を作成するにあたって、今までの課題を分けて作成していた場合、課題2～5の機能を追加すること」とありましたが、別々に作成して課題6で全て機能を追加するよりも課題2のソースを元に機能を追加していく方が効率的であると考えたので、課題4までの機能で使用している変数も入れておいたのですが、これは削除しておいた方がよいでしょうか？
3.更新しないカラムが空白になってしまう問題について：HTML側でupdateNameに値を代入する方法が思いつかなかったので、PHP側のソース17～26行目までで処理を行いました。

修正ありがとう！！

２に対しての返信です。
課題４までの機能で使用している変数は必要なのでそのままで大丈夫です！
こちらのコミットで不要なものが消えてるので解決済みです。

1d43f27

2020-07-29 15:33 UTC, jotasugiyama requested changes
> 検索結果を書き換え「更新」ボタンによってデータベースを更新する機能を追加する

と課題に記述されています。
検索結果後にセレクトボックスに表示されるIDは検索に引っかかったIDのみを選択できるようにしてください。

現状、検索結果に出てきてなくても違うレコードの情報を更新できてしまいます。↓
<img width="880" alt="スクリーンショット 2020-07-30 0 33 30" src="https://user-images.githubusercontent.com/46479112/88820456-4e123000-d1fc-11ea-9591-c6f15438190c.png">

2020-07-30 12:26 UTC, jotasugiyama approved these changes
Approveです！

2020-07-30 12:26 UTC, merged